services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    build: .
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin/servers.json
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./servers.json:/pgadmin/servers.json
      - ./web/pgadmin/static/js/generated:/pgadmin4/pgadmin/static/js/generated
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
